In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
print (np.__version__)

1.21.5


In [4]:
import numpy as np

In [5]:
a=np.array(10)
print(a)

10


In [6]:
a=np.array(100)
print(a)

100


In [7]:
a=np.array(1000)
print(a)


1000


In [8]:
a=np.array([10,20,30])
print(a)

[10 20 30]


In [9]:
a=np.array([[10,20],[30,40]])

In [10]:
print(a)

[[10 20]
 [30 40]]


In [11]:
a[1][0]

30

In [12]:
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a)            


[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [13]:
a=[10,20,30]

In [14]:
b=np.asarray(a,dtypa=int)
print(b)

TypeError: asarray() got an unexpected keyword argument 'dtypa'

In [14]:
#write a program in python to execute the "babble sart alogorithem"


In [ ]:
import as numpy np
